import Head from 'next/head';
import { useEffect } from 'react';
import Aos from 'aos';
import Header from '../components/Header';
import Homehero from '../components/Homehero';
import { HomeContainer } from '../styles/HomeStyles';
import 'aos/dist/aos.css';
import Experience from '../components/Experience';
import Projetos from '../components/Projetos';
import Conhecimentos from '../components/Conhecimentos';
import FormContato from '../components/FormContato';
import Footer from '../components/Footer';

export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 1500 });
  }, []);
  return (
    <HomeContainer>
      <Head>
        <title>Matheus H O</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />

      <main className="container">
        <Homehero />

        <div
          style={{
            width: '100%',
            borderBottom: '3px solid #0EE7B7'
          }}
        />

        <Experience />

        <Projetos />

        <div
          style={{
            width: '100%',
            borderBottom: '3px solid #0EE7B7'
          }}
        />

        <Conhecimentos />

        <div
          style={{
            width: '100%',
            borderBottom: '3px solid #0EE7B7'
          }}
        />

        <FormContato />
      </main>
      <Footer />
    </HomeContainer>
  );
}
