import Head from 'next/head';

import bonequinhoComBolsas from '../assets/cliente_w.png';
import Logo from '../assets/logo.svg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matheus H O</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>Olá mundo</h1>
        <img src={bonequinhoComBolsas} alt="Boneco" />
        <Logo />
      </main>
    </div>
  );
}
